Sshdisablecommunication
soltecsis/fwcloud-api pull request #660
Opened 2022-09-30 07:13 UTC by soltecsis-iortega

Closes #658

2022-09-30 11:41 UTC, soltecsis-jurios requested changes

2022-09-30 11:41 UTC, soltecsis-jurios commented on src/communications/ssh.communication.ts
> +            if(!app().config.get('session.ssh_enable')) {
Why don't use `this.getConfigValue()`?

2022-09-30 11:41 UTC, soltecsis-jurios commented on src/communications/ssh.communication.ts
> +            if(!app().config.get('session.ssh_enable')) {
Why don't use `this.getConfigValue()`?

2022-09-30 11:41 UTC, soltecsis-jurios commented on src/communications/ssh.communication.ts
> +            if(!app().config.get('session.ssh_enable')) {
Why don't use `this.getConfigValue()`?

2022-09-30 11:41 UTC, soltecsis-jurios commented on src/communications/ssh.communication.ts
> +            if(!app().config.get('session.ssh_enable')) {
Why don't use `this.getConfigValue()`?

2022-09-30 11:41 UTC, soltecsis-jurios commented on src/controllers/firewalls/firewall.controller.ts
> +        //Hay que tener cuidado de como se obtienen los datos y demas pero bueno ya estaria
Remove comment

2022-09-30 11:41 UTC, soltecsis-jurios commented on src/controllers/firewalls/firewall.controller.ts
> +    async configCommunication(request: Request): Promise<ResponseBuilder> {
We can provide this value when the UI is getting the data about the `fwcloud` (as this config value is `fwcloud`-related config parameter) and save this extra request.

2022-10-05 10:51 UTC, cmunyoz approved these changes

2022-10-06 08:29 UTC, merged