Systemctl management api
soltecsis/fwcloud-api pull request #730
Opened 2023-10-30 19:26 UTC by soltecsis-jfernandez

Close #726

2023-10-30 19:45 UTC, cmunyoz commented on src/controllers/firewalls/dtos/systemctl.dto.ts
> +    Copyright 2022 SOLTECSIS SOLUCIONES TECNOLOGICAS, SLU
Change the year to 2023

2023-10-30 19:45 UTC, cmunyoz commented on src/communications/agent.communication.ts
> +            const response: AxiosResponse<SystemCtlInfo> = await axios.post(pathUrl, systemCtlInfo, this.config);
The awaited response is of type `String` not of type `SystemCtlInfo`

2023-10-30 19:45 UTC, cmunyoz commented on src/controllers/firewalls/firewall.controller.ts
> +    }*/
Remove this comment block because it is useless.

2023-10-30 19:45 UTC, cmunyoz commented on src/communications/ssh.communication.ts
> +    }
We must implement this method for the SSH communication.
Its quite simple, look at other similar methods.

2023-11-02 15:59 UTC, cmunyoz commented
The route used for the `systemctl` API call is incorrect because we duplicating parameters for the `fwcloud` and `firewall` identifiers. The way that is implemented now the API call receives these parameters in que query string and in the body:
`http://localhost:3030/api/fwclouds/92/firewalls/937/systemctl`
<img width="636" alt="Captura de pantalla 2023-11-02 a las 16 57 47" src="https://github.com/soltecsis/fwcloud-api/assets/28894874/96f7cc35-82b2-4291-85af-0d722004d551">

- [ ] Change the route in a such way that the calling URL be: `http://localhost:3030/api/systemctl`

2023-11-07 10:57 UTC, soltecsis-iortega requested changes

2023-11-07 10:57 UTC, soltecsis-iortega commented on src/communications/agent.communication.ts
> +import { command } from "yargs";
You can delete the unused imports

2023-11-07 10:57 UTC, soltecsis-iortega commented on src/communications/agent.communication.ts
> +               // console.log("DATA", response.data)
You can delete the commented out console.log

2023-11-07 10:57 UTC, soltecsis-iortega commented on src/communications/ssh.communication.ts
> +            //console.log("response", response)
You can delete the commented out console.log

2023-11-07 10:57 UTC, soltecsis-iortega commented on src/controllers/systemctl/systemctl.controller.ts
> +export enum serviceOptions {
Could it be declared somewhere else?

2023-11-07 10:57 UTC, soltecsis-iortega commented on src/controllers/systemctl/systemctl.controller.ts
> +  export enum commandOptions {
Could it be declared somewhere else?

2023-11-07 10:57 UTC, soltecsis-iortega commented on src/routes/routes.ts
> +                            router.post('/systemctl', FirewallController,'systemctlCommunication').name('fwclouds.firewalls.communication.systemctlCommunication')
It's no longer used here

2023-11-07 12:54 UTC, soltecsis-iortega approved these changes

2023-11-23 09:35 UTC, merged